In [1]:
import numpy as np
import matplotlib.pyplot as plt
from keras.utils import np_utils
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import csv
from sklearn.utils import shuffle


In [2]:
# citire imagini de antrenare plus etichete de antrenare
f = open ("train.txt")
train_images = []
train_labels = []
for line in enumerate(open("train.txt", "r")):
    v = line[1].split(',')
    image_name = 'train/'+v[0]
    label = int(v[1])
    train_labels.append(label)
    image = plt.imread(image_name)
    train_images.append(image)
    
train_images = np.expand_dims(train_images, axis=3)
train_labels = np.array(train_labels)

train_images, train_labels = shuffle(train_images, train_labels, random_state=0)

(30001, 32, 32, 1)


In [3]:
# citire imagini de testare 
f = open ("test.txt")
test_images = []
name_test_images =[]
for line in enumerate(open("test.txt", "r")):
    image_name = 'test/'+ line[1][:len(line[1])-1]
    name_test_images.append(line[1][:len(line[1])-1])
    image = plt.imread(image_name)
    test_images.append(image)
    
test_images = np.expand_dims(test_images, axis=3)

In [4]:
# citire imagini de validare plus etichete de validare
f = open ("validation.txt")
validation_images = []
validation_labels = []
for line in enumerate(open("validation.txt", "r")):
    v = line[1].split(',')
    image_name = 'validation/'+v[0]
    label = int(v[1])
    label = v[1]
    validation_labels.append(label)
    image = plt.imread(image_name)
    validation_images.append(image)

validation_images = np.expand_dims(validation_images, axis=3)
validation_labels = np.array(validation_labels)

#validation_images, validation_labels = shuffle(validation_images, validation_labels, random_state=0)

In [5]:
nb_classes = 9 #9 categorii notate de la 0 la 8
print(train_images.shape)
print(validation_images.shape)
print(train_labels)

x_train=train_images
x_val=validation_images
test_images=test_images

y_val=np_utils.to_categorical(validation_labels, nb_classes) 
y_train=np_utils.to_categorical(train_labels, nb_classes) 


(30001, 32, 32, 1)
(5000, 32, 32, 1)
[1 4 1 ... 6 4 6]
[[[0.9647059 ]
  [0.8862745 ]
  [0.34509805]
  ...
  [0.99607843]
  [0.99607843]
  [0.99607843]]

 [[0.9607843 ]
  [0.9137255 ]
  [0.4       ]
  ...
  [0.99607843]
  [0.99607843]
  [1.        ]]

 [[0.96862745]
  [0.9490196 ]
  [0.33333334]
  ...
  [0.9843137 ]
  [0.99607843]
  [1.        ]]

 ...

 [[0.8392157 ]
  [0.84313726]
  [0.8784314 ]
  ...
  [1.        ]
  [1.        ]
  [1.        ]]

 [[0.87058824]
  [0.84313726]
  [0.74509805]
  ...
  [1.        ]
  [1.        ]
  [0.99607843]]

 [[0.89411765]
  [0.8235294 ]
  [0.7529412 ]
  ...
  [1.        ]
  [0.99607843]
  [0.9647059 ]]]


In [17]:
model = keras.Sequential()

model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

model.add(layers.Flatten())
model.add(layers.Dense(500, activation='relu'))
model.add(layers.Dropout(0.4))
model.add(layers.Dense(nb_classes, activation='softmax'))


model.summary()
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=32, epochs=15, verbose=1, validation_data=(x_val, y_val))



Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_21 (Conv2D)           (None, 30, 30, 32)        320       
_________________________________________________________________
max_pooling2d_14 (MaxPooling (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_22 (Conv2D)           (None, 13, 13, 64)        18496     
_________________________________________________________________
max_pooling2d_15 (MaxPooling (None, 6, 6, 64)          0         
_________________________________________________________________
conv2d_23 (Conv2D)           (None, 4, 4, 64)          36928     
_________________________________________________________________
flatten_7 (Flatten)          (None, 1024)              0         
_________________________________________________________________
dense_19 (Dense)             (None, 500)              

In [18]:
predict =model.predict_classes(test_images).astype("int32")
f = open("submission_3.csv", "w", newline="")
csv_file= csv.writer(f, delimiter=",")
csv_file.writerow(['id', 'label'])
for i in range (predict.shape[0]):
    print(name_test_images[i], ",", predict[i], sep="")
    csv_file.writerow([name_test_images[i], predict[i]])
f.close()

D:\Anaconda\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


035001.png,5
035002.png,0
035003.png,7
035004.png,7
035005.png,7
035006.png,0
035007.png,4
035008.png,7
035009.png,7
035010.png,7
035011.png,1
035012.png,5
035013.png,5
035014.png,1
035015.png,4
035016.png,1
035017.png,3
035018.png,4
035019.png,8
035020.png,6
035021.png,0
035022.png,0
035023.png,5
035024.png,8
035025.png,4
035026.png,4
035027.png,3
035028.png,5
035029.png,8
035030.png,3
035031.png,5
035032.png,0
035033.png,1
035034.png,1
035035.png,3
035036.png,7
035037.png,2
035038.png,6
035039.png,6
035040.png,0
035041.png,3
035042.png,6
035043.png,0
035044.png,0
035045.png,3
035046.png,5
035047.png,5
035048.png,3
035049.png,3
035050.png,1
035051.png,0
035052.png,2
035053.png,7
035054.png,1
035055.png,1
035056.png,7
035057.png,7
035058.png,7
035059.png,4
035060.png,1
035061.png,6
035062.png,4
035063.png,6
035064.png,8
035065.png,3
035066.png,4
035067.png,4
035068.png,2
035069.png,3
035070.png,1
035071.png,3
035072.png,1
035073.png,7
035074.png,6
035075.png,6
035076.png,4
035077.png,0

035715.png,5
035716.png,0
035717.png,5
035718.png,4
035719.png,2
035720.png,1
035721.png,0
035722.png,7
035723.png,1
035724.png,4
035725.png,8
035726.png,6
035727.png,1
035728.png,0
035729.png,1
035730.png,1
035731.png,8
035732.png,0
035733.png,3
035734.png,0
035735.png,3
035736.png,6
035737.png,8
035738.png,3
035739.png,4
035740.png,1
035741.png,6
035742.png,4
035743.png,2
035744.png,5
035745.png,0
035746.png,1
035747.png,4
035748.png,6
035749.png,5
035750.png,1
035751.png,8
035752.png,2
035753.png,8
035754.png,7
035755.png,5
035756.png,8
035757.png,3
035758.png,5
035759.png,5
035760.png,2
035761.png,2
035762.png,3
035763.png,5
035764.png,0
035765.png,6
035766.png,3
035767.png,7
035768.png,5
035769.png,3
035770.png,5
035771.png,4
035772.png,3
035773.png,6
035774.png,3
035775.png,3
035776.png,8
035777.png,6
035778.png,4
035779.png,1
035780.png,7
035781.png,1
035782.png,1
035783.png,8
035784.png,6
035785.png,6
035786.png,3
035787.png,4
035788.png,8
035789.png,4
035790.png,8
035791.png,5

036381.png,3
036382.png,7
036383.png,7
036384.png,4
036385.png,8
036386.png,1
036387.png,0
036388.png,0
036389.png,5
036390.png,2
036391.png,2
036392.png,4
036393.png,6
036394.png,3
036395.png,8
036396.png,3
036397.png,1
036398.png,0
036399.png,0
036400.png,5
036401.png,4
036402.png,4
036403.png,5
036404.png,7
036405.png,2
036406.png,5
036407.png,8
036408.png,8
036409.png,2
036410.png,3
036411.png,2
036412.png,2
036413.png,4
036414.png,0
036415.png,6
036416.png,2
036417.png,2
036418.png,1
036419.png,6
036420.png,0
036421.png,1
036422.png,1
036423.png,0
036424.png,4
036425.png,6
036426.png,4
036427.png,6
036428.png,2
036429.png,8
036430.png,2
036431.png,0
036432.png,0
036433.png,2
036434.png,2
036435.png,2
036436.png,4
036437.png,6
036438.png,8
036439.png,6
036440.png,2
036441.png,1
036442.png,8
036443.png,6
036444.png,3
036445.png,1
036446.png,1
036447.png,2
036448.png,3
036449.png,6
036450.png,0
036451.png,5
036452.png,4
036453.png,4
036454.png,0
036455.png,0
036456.png,7
036457.png,7

037048.png,2
037049.png,0
037050.png,1
037051.png,7
037052.png,0
037053.png,6
037054.png,8
037055.png,5
037056.png,7
037057.png,6
037058.png,8
037059.png,2
037060.png,2
037061.png,7
037062.png,2
037063.png,0
037064.png,6
037065.png,4
037066.png,5
037067.png,2
037068.png,6
037069.png,3
037070.png,3
037071.png,6
037072.png,6
037073.png,0
037074.png,4
037075.png,4
037076.png,5
037077.png,0
037078.png,6
037079.png,3
037080.png,3
037081.png,8
037082.png,0
037083.png,8
037084.png,3
037085.png,8
037086.png,2
037087.png,4
037088.png,5
037089.png,8
037090.png,8
037091.png,5
037092.png,7
037093.png,7
037094.png,5
037095.png,5
037096.png,7
037097.png,5
037098.png,6
037099.png,7
037100.png,2
037101.png,6
037102.png,0
037103.png,3
037104.png,6
037105.png,5
037106.png,8
037107.png,2
037108.png,4
037109.png,6
037110.png,7
037111.png,2
037112.png,4
037113.png,7
037114.png,3
037115.png,8
037116.png,1
037117.png,5
037118.png,4
037119.png,8
037120.png,7
037121.png,7
037122.png,7
037123.png,3
037124.png,2

037714.png,2
037715.png,6
037716.png,8
037717.png,3
037718.png,5
037719.png,4
037720.png,4
037721.png,5
037722.png,1
037723.png,5
037724.png,4
037725.png,3
037726.png,3
037727.png,1
037728.png,0
037729.png,4
037730.png,1
037731.png,0
037732.png,1
037733.png,0
037734.png,1
037735.png,6
037736.png,8
037737.png,3
037738.png,4
037739.png,2
037740.png,0
037741.png,3
037742.png,2
037743.png,5
037744.png,5
037745.png,4
037746.png,2
037747.png,1
037748.png,0
037749.png,3
037750.png,0
037751.png,2
037752.png,8
037753.png,3
037754.png,1
037755.png,5
037756.png,6
037757.png,3
037758.png,2
037759.png,5
037760.png,8
037761.png,7
037762.png,7
037763.png,7
037764.png,2
037765.png,2
037766.png,5
037767.png,3
037768.png,8
037769.png,4
037770.png,5
037771.png,2
037772.png,3
037773.png,1
037774.png,7
037775.png,5
037776.png,2
037777.png,8
037778.png,3
037779.png,7
037780.png,6
037781.png,4
037782.png,1
037783.png,4
037784.png,2
037785.png,7
037786.png,0
037787.png,7
037788.png,1
037789.png,1
037790.png,7

038381.png,1
038382.png,6
038383.png,8
038384.png,4
038385.png,6
038386.png,8
038387.png,4
038388.png,8
038389.png,1
038390.png,0
038391.png,0
038392.png,3
038393.png,3
038394.png,0
038395.png,3
038396.png,6
038397.png,5
038398.png,5
038399.png,0
038400.png,1
038401.png,5
038402.png,8
038403.png,7
038404.png,8
038405.png,6
038406.png,4
038407.png,6
038408.png,0
038409.png,2
038410.png,7
038411.png,5
038412.png,0
038413.png,4
038414.png,5
038415.png,1
038416.png,3
038417.png,2
038418.png,1
038419.png,8
038420.png,7
038421.png,8
038422.png,1
038423.png,5
038424.png,6
038425.png,8
038426.png,5
038427.png,8
038428.png,1
038429.png,6
038430.png,8
038431.png,0
038432.png,5
038433.png,5
038434.png,4
038435.png,1
038436.png,8
038437.png,5
038438.png,1
038439.png,0
038440.png,7
038441.png,2
038442.png,5
038443.png,4
038444.png,0
038445.png,0
038446.png,7
038447.png,3
038448.png,7
038449.png,7
038450.png,1
038451.png,2
038452.png,4
038453.png,7
038454.png,1
038455.png,4
038456.png,8
038457.png,2

039047.png,2
039048.png,4
039049.png,8
039050.png,7
039051.png,1
039052.png,2
039053.png,3
039054.png,5
039055.png,5
039056.png,7
039057.png,6
039058.png,4
039059.png,0
039060.png,7
039061.png,5
039062.png,0
039063.png,1
039064.png,0
039065.png,6
039066.png,6
039067.png,5
039068.png,6
039069.png,2
039070.png,7
039071.png,1
039072.png,6
039073.png,7
039074.png,3
039075.png,7
039076.png,4
039077.png,1
039078.png,7
039079.png,4
039080.png,2
039081.png,3
039082.png,0
039083.png,8
039084.png,6
039085.png,0
039086.png,8
039087.png,5
039088.png,5
039089.png,5
039090.png,3
039091.png,6
039092.png,6
039093.png,6
039094.png,4
039095.png,1
039096.png,0
039097.png,7
039098.png,2
039099.png,1
039100.png,7
039101.png,1
039102.png,5
039103.png,5
039104.png,5
039105.png,5
039106.png,2
039107.png,4
039108.png,1
039109.png,5
039110.png,4
039111.png,2
039112.png,2
039113.png,8
039114.png,3
039115.png,8
039116.png,4
039117.png,3
039118.png,1
039119.png,5
039120.png,2
039121.png,8
039122.png,7
039123.png,4